### ISSUE TITLE
rfft 16 and cfft 8 support

### ISSUE THREAD

**Issue by bfs18** [ARM-software/CMSIS-DSP#101]
Hi, thanks for the great library. Are there any plan to support rfft 16 and cfft  8. Small fft size is desirable when the computing capability is extremely limited.

**Comment by christophe0606** [comment]
@bfs18 Sorry for the very late answer.
At this point we have no plan to support small FFT sizes.
You can open a github issue asking for an enhancement so that we have the task in our backlog.
