### ISSUE TITLE
Matrix Vector Multiplication fails for large matrix size

### ISSUE THREAD

**Issue by yuvpg** [ARM-software/CMSIS-DSP#118]
`arm_mat_vec_mult_f32()` fails to produce correct output if `rowCount`*`colCount` > 65536 

There is a bug in definition of a loop counter:
```
uint16_t i, row, colCnt; /* loop counters */    <-- should be uint32_t
```

https://github.com/ARM-software/CMSIS-DSP/blob/cb0960577d6483a2a626ae5d8778b6f00a844b32/Source/MatrixFunctions/arm_mat_vec_mult_f32.c#L301C5-L301C14

**Comment by christophe0606** [comment]
@yuvpg Thanks for reporting this.

**Comment by christophe0606** [comment]
It should be fixed in latest commit.
