### ISSUE TITLE
package build one single problem

### ISSUE THREAD

**Issue by tdjastrzebski** [ARM-software/CMSIS-DSP#122]
It is a great package with one single yet significant issue.
For no apparent reason it is completely dependent on one particular build tool (CMAKE) and requires significant effort to compile with anything else.

**Comment by christophe0606** [comment]
@tdjastrzebski The README is explaining how to build with a Makefile.
It is also explaining how to adapt to other build tools : https://github.com/ARM-software/CMSIS-DSP#how-to-build-with-any-other-build-system

and it is also supporting CMSIS build tools.

**Comment by tdjastrzebski** [comment]
@christophe0606 Thank you, I admit that I missed that.
It may be a good idea to instead of removing/excluding `xxFunctions.c` files, put their content in (e.g.) blocks like this
```
#if defined(COMPILE_xxFUNCTIONS_FILES_ONLY)
//
#endif
```
or
```
#if !defined(COMPILE_ALL)
//
#endif
```
