### ISSUE TITLE
error: inlining failed in call to always_inline 'vfmaq_f32'

### ISSUE THREAD

**Issue by dushen272** [ARM-software/CMSIS-DSP#123]
when I built the library with "Xilinx ARM v7 GNU Toolchain", I encountered some issues.
Following is the building log:

[CMSIS-DSP_Library_Debug.build.ui.log](https://github.com/ARM-software/CMSIS-DSP/files/13222704/CMSIS-DSP_Library_Debug.build.ui.log)

Can anyone help me to solve this issue, thanks.

**Comment by Nangongchen** [comment]
Hi, I had the same issue with cortex-a9,could you please share the solution?
