### ISSUE TITLE
arm_mat_qr_f32

### ISSUE THREAD

**Issue by yanlong658** [ARM-software/CMSIS-DSP#126]
Hello,
I have a question about the arm_mat_qr_f32 function regarding the threshold parameter. It appears that the threshold must be specified as a negative value. Is this intentional, or does it differ from the typical practice of using positive values for thresholds in similar functions?

Thanks all.

**Comment by christophe0606** [comment]
@yanlong658 Hello,

The threshold is positive. For instance, it can be one of the thresholds defined in the header `dsp/matrix_functions.h`

```C
#define DEFAULT_HOUSEHOLDER_THRESHOLD_F64 (1.0e-16)
#define DEFAULT_HOUSEHOLDER_THRESHOLD_F32 (1.0e-12f)
```

**Comment by yanlong658** [comment]
Hello sir,

I have find it.

Thank you
