### ISSUE TITLE
DSP library to Crotex-R5

### ISSUE THREAD

**Issue by kalisheep** [ARM-software/CMSIS-DSP#129]
Is it feasible to transplant the DSP library to Crotex R5 and how to obtain an acceleration library,

**Comment by christophe0606** [comment]
@kalisheep CMSIS-DSP relies on CMSIS-Core for DSP intrinsic support on several compilers.
There is not yet Cortex-R support in CMSIS-Core but it is a work in progress in this pull request:

https://github.com/ARM-software/CMSIS_6/pull/45
