### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ARM-software/CMSIS-DSP#132]
I would like to point out that identifiers like “[`_MATRIX_UTILS_H_`](https://github.com/ARM-software/CMSIS-DSP/blob/99e15d3d95084b6868c5579b6791aff5cbeefcd6/Include/dsp/matrix_utils.h#L27-L28 "Update candidate")” and “[`_TRANSFORM_FUNCTIONS_H_`](https://github.com/ARM-software/CMSIS-DSP/blob/99e15d3d95084b6868c5579b6791aff5cbeefcd6/Include/dsp/transform_functions.h#L27-L28 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by christophe0606** [comment]
@elfring Have you observed any name clash with reserved names ?

**Comment by elfring** [comment]
:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by escherstair** [comment]
According to C standard, [rule 7.1.3](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) states

> Do not declare or define a reserved identifier
>     All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use.
>     All identifiers that begin with an underscore are always reserved for use as identifiers with file scope in both the ordinary and tag name spaces.
>     Each macro name in any of the following subclauses (including the future library directions) is reserved for use as specified if any of its associated headers is included, unless explicitly stated otherwise.
>     All identifiers with external linkage (including future library directions) and errno are always reserved for use as identifiers with external linkage.
>     Each identifier with file scope listed in any of the following subclauses (including the future library directions) is reserved for use as a macro name and as an identifier with file scope in the same name space if any of its associated headers is included.

I would appreciate if CMSIS DSP headers could be made compliant to this rule.

**Comment by christophe0606** [comment]
Done in commit https://github.com/ARM-software/CMSIS-DSP/commit/69d4b8ed8d3271facb2daff94216f7981774e816

**Comment by elfring** [comment]
:crystal_ball: Do [name conventions for C++ code](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") matter for your software?
