### ISSUE TITLE
const-qualify interp_instance structs in interpolation functions

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS-DSP#133]
Interpolation functions take as an input an `interp_instance` struct.
As an example,
https://github.com/ARM-software/CMSIS-DSP/blob/99e15d3d95084b6868c5579b6791aff5cbeefcd6/Source/InterpolationFunctions/arm_linear_interp_f32.c#L79-L81

As far as I understand, this `interp_instance` is not modified by the function, and so the pointer can be declared as `pointer to const`.
```C
float32_t arm_linear_interp_f32(
  const arm_linear_interp_instance_f32 * S,
  float32_t x)
```
In this way the code is more expressive, and a `const` struct can be passed as an input without any warning about casting-away its const-ness.

**Comment by christophe0606** [comment]
Corrected in latest commit
