### ISSUE TITLE
CMSIS-DSP for Arm® Cortex®-A53

### ISSUE THREAD

**Issue by Adrillanos** [ARM-software/CMSIS-DSP#153]
Hi, I am interested in using this library for the Arm® Cortex®-A53
I have seen that someone already asked about this a few years ago. 

https://github.com/ARM-software/CMSIS_5/issues/983

It looks like Christophe0606 managed to migrate it to the A53, I wanted to ask if there is already a open source version of this that I can use or some documentation on how to do this.

Thank you,
Adrián

**Comment by christophe0606** [comment]
Hi, @Adrillanos 

You can look at [how to build for aarch64](https://github.com/ARM-software/CMSIS-DSP?tab=readme-ov-file#how-to-build-for-aarch64) in the README.

We have some Neon acceleration. Nearly no aarch64 acceleration.
And no Neon for the FFTs.

We hope to add more Neon support in the future.
