### ISSUE TITLE
Missing implementation for arm_fir_decimate_f64

### ISSUE THREAD

**Issue by torfinnberset** [ARM-software/CMSIS-DSP#154]
Currently, there is an implementation for `arm_fir_f64`, but there is no equivalent `arm_fir_decimate_f64` as there are with the f32 variants of the same functions. 

I could provide a reference implementation PR based on arm_fir_decimate_f32 if desired (removing any f32 intrinsic optimizations)

**Comment by christophe0606** [comment]
@torfinnberset Thanks. Don't hesitate to submit PR.
Note that currently I won't be able to quickly test / merge your PR because I am working on other things. But I'll do as soon as I can find some bandwidth.
