### ISSUE TITLE
Element-wise division

### ISSUE THREAD

**Issue by dalim-winegard** [ARM-software/CMSIS-DSP#155]
Hi,

Just wanted to check and see if there ever was an element-wise division function implemented in CMSIS DSP.

Thanks.

**Comment by christophe0606** [comment]
@dalim-winegard Hi,
No because there is no way to accelerate it. I mean it would be equivalent to a normal C loop. So we did not consider this function for inclusion in the library.

**Comment by dalim-winegard** [comment]
@christophe0606 Noted, thanks for your answer!
