### ISSUE TITLE
CppCheck giving warning for arm_divide_q31 because of CWE 758 violation

### ISSUE THREAD

**Issue by marcluque** [ARM-software/CMSIS-DSP#165]
I encountered a warning from CppCheck indicating the the following line of [arm_divide_q31.c#L66](https://github.com/ARM-software/CMSIS-DSP/blob/main/Source/FastMathFunctions/arm_divide_q31.c#L66) is violating [CWE 758](https://cwe.mitre.org/data/definitions/758.html).
CppCheck message:
```
cppcheck version="2.5"
msg="Shifting signed 32-bit value by 31 bits is implementation-defined behaviour"
cwe="758"
```

This will also hold for q15 I think.

I suppose that something like `(numerator < 0) ^ (denominator < 0)` could fix it?

**Comment by christophe0606** [comment]
Corrected in latest commit

**Comment by marcluque** [comment]
Very nice, thanks for the quick turnaround! I'll close this issue then.
