### ISSUE TITLE
Redirect to DSP hardware

### ISSUE THREAD

**Issue by liuyuxivapor** [ARM-software/CMSIS-DSP#167]
Hi, there. 

I am using an MCU with a Cortex-M4F processor and a DSP hardware. Is it possible to redirect this package to DSP hardware to make it faster(perhaps) to calculate? Should I do sth on **this package, MCU, or DSP**?

Thanks a lot if anyone could help me with this!

**Comment by christophe0606** [comment]
@liuyuxivapor Hi,
It is a cortex-M and A library only.
