### ISSUE TITLE
arm_svm_polynomial_predict_f32.c error

### ISSUE THREAD

**Issue by Q1anWan** [ARM-software/CMSIS-DSP#190]
It seems that when building with **option(NEON "Neon acceleration" ON)** and **option(AUTOVECTORIZE "Prefer autovectorizable code to one using C intrinsics" ON)**, the **arm_vec_exponent_f32** function is not defined, which will cause error in **arm_svm_polynomial_predict_f32.c** line 407.

**Comment by christophe0606** [comment]
@Q1anWan You're right. It looks like the `ARM_MATH_AUTOVECTORIZE` test is not applied coherently to all Neon versions. The `arm_svm_polynomial_predict_f32` is not disabled with `ARM_MATH_AUTOVECTORIZE`  but it should.
