### ISSUE TITLE
Why DSP is not enabled in arm dot prod q15.

### ISSUE THREAD

**Issue by majorlin** [ARM-software/CMSIS-DSP#195]
https://github.com/ARM-software/CMSIS-DSP/blob/7236701c153c9bbdec00568a2821a39039988d8f/Source/BasicMathFunctions/arm_dot_prod_q15.c#L154

**Comment by christophe0606** [comment]
@majorlin Thanks for finding this.

I don't see any good reason for this. It is a very old change in the library.

**Comment by christophe0606** [comment]
@majorlin I correct what I have just said. I `__SMLALD` requires two Q15 packed in an int32.
But this line is using `*pSrcA++` to read a q15 from the tail of the vector.

So the instruction `__SMLALD` cannot be used here.
