### ISSUE TITLE
arm_mat_init_f64 exists but has been omitted from MatrixFunctions/Config.cmake

### ISSUE THREAD

**Issue by TG-PST** [ARM-software/CMSIS-DSP#214]
CMSIS-DSP\Source\MatrixFunctions\Config.cmake is missing MatrixFunctions/arm_mat_init_f64.c in the SRCF64 list of source files.

**Comment by christophe0606** [comment]
Thanks !

**Comment by christophe0606** [comment]
Corrected in commit https://github.com/ARM-software/CMSIS-DSP/commit/c410a2c8f0beacb1b3d6f4d0960ccf4fc1f73c4c
