### ISSUE TITLE
Function vuninitializedq_s16 has no prototype

### ISSUE THREAD

**Issue by RemiCSTM** [ARM-software/CMSIS-DSP#215]
Hi, I am currently working with the <arm_math.h> library and when I try to compile it with IAR, I get this compilation error:

```
      vecDst = vuninitializedq_s16();
               ^
\cmsis_dsp\Include\arm_helium_utils.h",684  Error[Pa045]: function "vuninitializedq_s16" has no prototype
```

I did not find any implementation for this function.

**Comment by christophe0606** [comment]
@RemiCSTM It looks like a problem with the compiler since this intrinsics is part of the C interface in `arm_mve.h` and I have just checked it is defined in gcc, clang and Arm compiler 6:

[vuninitializedq_s16](https://developer.arm.com/architectures/instruction-sets/intrinsics/#f:@navigationhierarchiessimdisa=[Helium]&q=vuninitializedq_s16)

**Comment by jeromecoutant** [comment]
In <iar toolchain>/inc/c/aarch32/arm_mve.h, I can see:
````
static __inline__ __attribute__((__clang_arm_builtin_alias(__builtin_arm_mve_vuninitializedq_s16)))
int16x8_t vuninitializedq_s16();
````
Seems IAR is not well managing `__attribute__((__clang_arm_builtin_alias(__builtin_arm_mve_vuninitializedq_s16)))` ?



````
$ /opt/iarsystems/bxarm/arm/bin/iccarm  /xxx/Source/BayesFunctions/BayesFunctionsF16.c  -I/xxx/cmsis/CMSIS/Core/Include -I/xxx/cmsis_dsp/Include -I/xxx/cmsis_dsp/PrivateInclude --cpu=Cortex-M85 --fpu=VFPv5_d16 --endian=little --cmse  -Ohz --debug --dlib_config DLib_Config_Full.h --no_wrap_diagnostics -e --enable_restrict --vla --require_prototypes --dependencies=ns xxx/cmsis_dsp/Source/BayesFunctions/BayesFunctionsF16.o.d -o xxx/cmsis_dsp/Source/BayesFunctions/BayesFunctionsF16.o

      vecDst = vuninitializedq_s16();
               ^
"/xxx/cmsis_dsp/Include/arm_helium_utils.h",684  Error[Pa045]: function "vuninitializedq_s16" has no prototype

Errors: 1
Warnings: none
````

**Comment by christophe0606** [comment]
@jeromecoutant I don't know IAR. I assume it ignores clang attributes ? Perhaps a copy / paste from clang mve header when they started working on MVE ?

**Comment by jeromecoutant** [comment]
@jlonnberg
