### ISSUE TITLE
how to get atan2_coefs_f32?

### ISSUE THREAD

**Issue by Quintin-Z** [ARM-software/CMSIS-DSP#218]
Could you please help me with this? How are the coefficients of the arm_atan_limited_f32 function obtained? Are they derived from polynomial curve fitting or Taylor expansion? I used MATLAB to generate the curve over the interval [0, 1] and performed fitting, but I found that the obtained coefficients do not match those in the code.

static const float32_t atan2_coefs_f32[ATAN2_NB_COEFS_F32]={0.0f
,1.0000001638308195518f
,-0.0000228941363602264f
,-0.3328086544578890873f
,-0.004404814619311061f
,0.2162217461808173258f
,-0.0207504842057097504f
,-0.1745263362250363339f
,0.1340557235283553386f
,-0.0323664125927477625f
};

**Comment by christophe0606** [comment]
@Quintin-Z It is a polynomial produced using minimax approximation. The Remez algorithm is used.

You probably won't be able to exactly reproduce the coefficients but you should be able to produce a polynomial with same error bound on the interval [0,1]

**Comment by Quintin-Z** [comment]
i got it，thank you very much！Mr. Favergeon
