### ISSUE TITLE
PythonWrapper segmentation fault using arm_biquad_cas_df1_32x64 

### ISSUE THREAD

**Issue by erlenfas** [ARM-software/CMSIS-DSP#224]
Segmentation fault occurs in arm_biquad_cas_df1_32x64_init_q31 when using the cmsisdsp python wrapper.

**Comment by christophe0606** [comment]
@erlenfas On which computer ? Windows x86 ? Linux x86 ? Mac apple silicon  ?

Do you have a small Python script to reproduce the problem ?

**Comment by erlenfas** [comment]
Hi @christophe0606 - trying to figure out if I can make a PR. Found and fixed the problem. The problem will be present for all architectures, I have tested on x64 MacOS and arm64 MacOS

**Comment by christophe0606** [comment]
I merged the PR. Thank you !
