### ISSUE TITLE
Controlling optimization levels

### ISSUE THREAD

**Issue by ehughes** [ARM-software/CMSIS-DSP#46]
I generally like to build CMSIS DSP with optimizations.      Right now I am doing something like this:

`target_compile_options(CMSISDSP PUBLIC "-03")`

in my CmakeLists.txt

Is there a better option?

**Comment by christophe0606** [comment]
I am leaving this choice to the user of the library and nothing is imposed by the library itself. But it is true that the library should be compiled with -Ofast or -O3.
