### ISSUE TITLE
GCC error - missing cast in MVE arm_biquad_cascade_df1_q15

### ISSUE THREAD

**Issue by kjbracey** [ARM-software/CMSIS-DSP#58]
We've had a report that GCC doesn't like the MVE version of arm_biquad_cascade_df1_q15. And its complaint seems valid:

https://github.com/ARM-software/CMSIS-DSP/blob/302897a523f5abae63fae9bdb3bbfc1e3089a55a/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c#L105-L108

> arm_biquad_cascade_df1_q15.c:106:13: error: incompatible types when assigning to type 'q15x8_t' {aka 'int16x8_t'} from type 'int32x4_t'

I'd say you need an explicit `(q15x8_t)` cast on the output of `vsetq_lane_s32`.

What's not clear to me is why armclang accepts it, which it does. Indeed, armclang doesn't seem to require the existing `(q31x4_t)` casts either, at least within that C file.

Pasting the same function into some other C++ code I had handy made armclang produce the equivalent error, unless you have 3 casts. Is it performing implicit conversion in C mode, maybe? Intentionally? Possible armclang bug?

**Comment by kjbracey** [comment]
While looking around build systems, I've just noticed that GCC's behaviour here is configurable via `-flax-vector-conversions`.

**Comment by christophe0606** [comment]
It is advised to use `-flax-vector-conversions` because there are some cases where the use of the intrinsic is valid but gcc is nevertheless generating a warning.

But, I'll look at above case because I think it needs the cast.

**Comment by kjbracey** [comment]
Any thoughts on the C vs C++ difference in armclang (if that's what it is)? I don't see such a thing documented. Can you control it?

**Comment by christophe0606** [comment]
I don't know the differences between C and C++ for handling the intrinsics.

So you confirm that for the `arm_biquad_cascade_df1_q15`,  you get cast warnings in C++ with armclang but none from C ?

Can you share the compilation options you used ? I'll try to reproduce and then check with our compiler team.

**Comment by kjbracey** [comment]
Yes, I've stripped it down, and confirm that it's a C/C++ difference

Given this source:

    #include "arm_mve.h"

    int16x8_t test(int32x4_t a)
    {
        return a;
    }

That's accepted if it's input as C:

    armclang --target=arm-arm-none-eabi -mcpu=cortex-m55 -O2 -S vectest.c

But rejected with the type error if it comes in as `vectest.cpp`. Compiler version 6.18.

**Comment by christophe0606** [comment]
Compiler team tells me that the C and C++ standards are not managing implicit casts in the same way. But otherwise, for this specific example they can't say more.

**Comment by kjbracey** [comment]
Arm C Language Extensions document just says that such implicit conversions are not portable (for C or C++) - and to use `vreinterpretq`. (It doesn't actually say explicit conversions via casts are portable.)

So the C compiler is free to give the error, and I think it would be far more helpful if it did. Was trying to check whether this has changed since `armcc`, but don't have a copy to hand.

**Comment by kjbracey** [comment]
Minor update, as I found some discussion elsewhere - clang and armclang do also have the `-flax-vector-conversions` flag, slightly extended to support three options: `=none`, `=int`, `=all`.

Documentation for clang says the default is `-flax-vector-conversions=int` = `-flax-vector-conversions`, but as we saw above, the default is actually `none` for C++.

You can get armclang to reject the above code in C by adding `-flax-vector-conversions=none` or `-fno-lax-vector-conversions`. I'll be adding that to my own projects. (I've made too many mistakes from its absence!)

Which in turn means that the change in #65 technically needs to also be applied for armclang.  If someone has made vectors strict in the global CMake compile flags (or a future clang has tightened up), it needs to be overridden for the CMSIS-DSP target.

**Comment by christophe0606** [comment]
@kjbracey Thanks for the feedback !

**Comment by christophe0606** [comment]
@kjbracey I have added a cmake option to enable / disable lax vector conversions when building for Helium with gcc or ArmClang.
By default it is ON since currently some parts of the library won't build without it.

**Comment by christophe0606** [comment]
@kjbracey You're right. It build without problems with `integer`. I have just pushed the change.
