### ISSUE TITLE
MVE arm_correlate_f32 may write to negative pDst index

### ISSUE THREAD

**Issue by stephanosio** [ARM-software/CMSIS-DSP#59]
MVE arm_correlate_f32 implementation may write to a negative pDst index (before the beginning of the pDst buffer).

This happens when `incr` is a negative number.

https://github.com/ARM-software/CMSIS-DSP/blob/e0bb1407f77efda1410d0792b3c32fd07e236cfb/Source/FilteringFunctions/arm_correlate_f32.c#L173

This is observed when running the following test cases:

https://github.com/ARM-software/CMSIS-DSP/blob/809202bf185280a322efc2e2c850a544747f9d79/Testing/Source/Tests/MISCF32.cpp#L134-L140

https://github.com/ARM-software/CMSIS-DSP/blob/809202bf185280a322efc2e2c850a544747f9d79/Testing/Source/Tests/MISCF32.cpp#L142-L148

https://github.com/ARM-software/CMSIS-DSP/blob/809202bf185280a322efc2e2c850a544747f9d79/Testing/Source/Tests/MISCF32.cpp#L214-L220

https://github.com/ARM-software/CMSIS-DSP/blob/809202bf185280a322efc2e2c850a544747f9d79/Testing/Source/Tests/MISCF32.cpp#L222-L228

https://github.com/ARM-software/CMSIS-DSP/blob/809202bf185280a322efc2e2c850a544747f9d79/Testing/Source/Tests/MISCF32.cpp#L302-L308

**Comment by christophe0606** [comment]
@stephanosio The problem is also present on fixed point versions.
Thanks for reporting it.

**Comment by christophe0606** [comment]
It should be corrected now.
