### ISSUE TITLE
Rework configuration of CMSIS-DSP build

### ISSUE THREAD

**Issue by christophe0606** [ARM-software/CMSIS-DSP#6]
Current configuration of build (to tune code size) is too complex.
It needs to be improved and also to avoid problems like https://github.com/ARM-software/CMSIS_5/issues/1478

**Comment by christophe0606** [comment]
This issue will no more be relevant when the configuration system has been reworked:
https://github.com/ARM-software/CMSIS_5/issues/1237

**Comment by stephanosio** [comment]
I would strongly suggest using Kconfig for this purpose:
https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/Kconfig.cmsis_dsp

**Comment by christophe0606** [comment]
@stephanosio  Thanks. I'll look at it.

**Comment by christophe0606** [comment]
Code size tuning now relying on linker and new initialization functions
