### ISSUE TITLE
Cortex-A53 (aarch64) issues

### ISSUE THREAD

**Issue by ua1arn** [ARM-software/CMSIS-DSP#73]
Can anybody fix these mistypes:
![image](https://user-images.githubusercontent.com/34999007/205605752-29fb27e2-24be-4ff3-9f8b-12988e671ec5.png)

Function argument are explict uint32_t *, but values not suitable...

**Comment by christophe0606** [comment]
@ua1arn In latest version it is using already `UINT_MAX` because, indeed, the `ULONG_MAX` was causing problems on aarch64.

**Comment by ua1arn** [comment]
Make sure:
uint32x4_t is a packed uint32_t, not unsigned (think about portability)

**Comment by ua1arn** [comment]
Possible portability issue.

**Comment by christophe0606** [comment]
I'll reopen if more data available like reproducer.
