### ISSUE TITLE
Python wrapper cmsis_arm_correlate_f32 wrong output calculation

### ISSUE THREAD

**Issue by a1lu** [ARM-software/CMSIS-DSP#76]
Hi,
the python wrapper calculates the output length like this:
```
uint32_t outputLength = 2*MAX(srcALen,srcBLen) - 1 ;
```
for 
```
int srcALen = 3;
int srcBLen = 8
```
The result is 8. Thats wrong.
On my side a fix is to wrap the MAX macro with braces

```
uint32_t outputLength = 2*(MAX(srcALen,srcBLen)) - 1 ;
```

**Comment by a1lu** [comment]
```
#define MAX(A, B) ((A) < (B) ? (B) : (A))
```

in `PythonWrapper/cmsisdsp_pkg/src/cmsisdsp_module.h` would fix this everywhere

**Comment by christophe0606** [comment]
@a1lu Thanks for feedback. I have merged the PR.
I don't update the binary versions of the wrapper too often but a new version will probably come in january.
