### ISSUE TITLE
Protect against MIn and MAX macro redefinition

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS-DSP#85]
`utils.h` define some common macros (`MIN` and `MAX`, as an example)
https://github.com/ARM-software/CMSIS-DSP/blob/1378fa94f5ccf8e0ec424d7da56807721139dfd1/Include/dsp/utils.h#L43-L45
Since they're quite common, it's happens that some other libraries try to define them.
And so the order of `.h` inclusion matters.

I suggest including them into define guards
```
#ifndef MIN
  #define MIN(x,y) ((x) < (y) ? (x) : (y))
#endif

#ifndef MAX
  #define MAX(x,y) ((x) > (y) ? (x) : (y))
#endif
```
to avoid this kind of warnings
`warning: 'MIN' macro redefined [-Wmacro-redefined]`
if in the order of `.h` inclusion, `utils.h` comes after another `.h` that defines `MIN` and `MAX` (even if this third party `.h` uses its own include guards, but it's included before `utils.h`)

**Comment by christophe0606** [comment]
@escherstair I totally agree. I have been faced to this problem recently. I'll make the change.
