### ISSUE TITLE
Extensive support for aarch64

### ISSUE THREAD

**Issue by jsksra1** [ARM-software/CMSIS-DSP#86]
It's been mentioned in this [thread#70](https://github.com/ARM-software/CMSIS-DSP/issues/70) that currently the 64 bit Neon support is very limited. 

Would like to know if there is any possible plan or timeline in supporting aarch64 extensively (all basic ops and math functions).

**Comment by christophe0606** [comment]
@jsksra1 So far the f64 is coming mainly from the users of CMSIS-DSP through PR.
We don't have any timeline for the optimizations or benchmarking of those functions.
